version: "2"
linters:
  default: all
  disable:
    - funcorder
    - nonamedreturns
    - varnamelen
  settings:
    cyclop:
      max-complexity: 13
    depguard:
      rules:
        main:
          list-mode: lax
          allow:
            - golang.org/x/crypto/*
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      enable-all: true
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    interfacebloat:
      max: 11
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
      ignored-numbers:
        - '2'
        - '3'
        - '4'
        - '8'
    nlreturn:
      block-size: 2
    prealloc:
      simple: false
      for-loops: true

  exclusions:
    rules:
      - path: internal/hash.go
        text: "Error return value of `h.h.Write` is not checked"
      - path: internal/tag/strings.go
        text: "G101: Potential hardcoded credentials"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/bytemare/opaque)
        - blank
        - dot
        - alias
      no-inline-comments: true
      no-prefix-comments: true
      custom-order: true
    goimports:
      local-prefixes:
        - github.com/bytemare/opaque
    golines:
      max-len: 200
output:
  sort-order:
    - file
run:
  tests: false