name: Snyk

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '31 10 * * 0'

permissions:
  contents: read

jobs:
  snyk:
    name: Snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # pin@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@e0bb9436303033a6ecc7f3d3af5e842c269a969d # pin@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
