name: Snyk

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '31 10 * * 0'

permissions:
  contents: read

jobs:
  snyk:
    name: Snyk
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@18f6947f131da60743dc12d2a22ff28c2b4ea87f
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.snyk.io:443
            github.com:443
            proxy.golang.org:443

      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@cdb760004ba9ea4d525f2e043745dfe85bb9077e
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
