name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.24' ]
    uses: bytemare/workflows/.github/workflows/test-go.yml@afad92d878aa59e09b531c895fa4c709bc420538
    with:
      command: cd .github && make test
      version: ${{ matrix.go }}
