name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.24' ]
    uses: bytemare/workflows/.github/workflows/test-go.yml@94b2aa6d146f0aa6c3610587fe1f1d057d3db117
    with:
      command: cd .github && make test
      version: ${{ matrix.go }}
